### ISSUE TITLE
Improve spliting into components

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/niagara-lang#13]
I would advise to split the code in 4 parts:

* `utils` (already exists)
* `parser` : a library with the AST, a textual parser and a textual printer
* `interpreter`: a library to execute the AST over data
* `niagara`: a command-line application to test the compiler/interpreter on source files

Important parts:
* neither `parser` nor `interpreter` should contain code that displays textual messages. For example, they could define a `error` type the list all possible errors, instead of raising `failwith` or similar textual operations. They should also never call `exit`, but raise an exception instead.

**Comment by Keryan-dev** [comment]
Splitting done :
- `commons` for general data structures that have uses across the board
- `surface` for source language AST
- `internal` for intermediary representation
- `grammar` for source code parsing
- `compiler` for the compilation pipeline
- `interpreter`
- and `exec` for the CLI executable

Removing explicit errors from the libraries should be a separate issue.
